### PR TITLE
Trust custom certificates/CA if you choose to

### PR DESCRIPTION
**Pull request by cytopia**

### CODE REVIEW

**Comment by science695** [comment]
My test shows that the files are not copied to /usr/local/share/ca-certificates/ properly.

Could there be a permissions issue? is the docker entry script running as non-root?

I tested with these overrides:
php:
  image: devilbox/php-fpm:7.1-work-release-0.15
  volumes:
    - ${DEVILBOX_PATH}/ca:/ca

**Comment by cytopia** [comment]
This one is php-fpm:7.1-work-release-0.17

**Comment by cytopia** [comment]
@science695 Images are available. You need to use this Devilbox branch: https://github.com/cytopia/devilbox/pull/269 as well as adjust the image tag in docker-compose.yml

**Comment by science695** [comment]
My test succeeded. Thanks!

**Comment by cytopia** [comment]
Nice, I will merge it and apply the Devilbox branch once those images are built in master.

**Pull request merged**
