### PR TITLE
Update url for pip 2.7

### PR DESCRIPTION
**Pull request by misterwalrus**
get-pip.py for Python 2.7 changed URL.   If not changed the image fails to build.

### CODE REVIEW

**Comment by llaville** [comment]
@misterwalrus Nice patch, but PHP 7.1 image did not built : Reason is [pecl/swoole requires PHP (version >= 7.2.0), installed version is 7.1.33](https://github.com/devilbox/docker-php-fpm/runs/1762237666?check_suite_focus=true#step:6:14451)

**Comment by llaville** [comment]
A quick fix to solve Swoole issue will be to disable it 

```
diff --git a/build/ansible/group_vars/all/mods.yml b/build/ansible/group_vars/all/mods.yml
index 6052bb2..ab41425 100644
--- a/build/ansible/group_vars/all/mods.yml
+++ b/build/ansible/group_vars/all/mods.yml
@@ -973,7 +973,7 @@ extensions_available:
       build_dep: [libssh2-1-dev]
       run_dep: [libssh2-1]
   swoole:
-    disabled: [5.2, 8.0, 8.1]
+    disabled: [5.2, 7.1, 8.0, 8.1]
     5.3:
       type: pecl
       version: 1.9.23
```

**Comment by llaville** [comment]
After checking Swoole versions, the best fixe should be to set correct version, rather than disable it for version 7.1 !

* last version of branch 4.5 that support PHP 7.1 is [4.5.11](https://github.com/swoole/swoole-src/blob/v4.5.11/package.xml#L1926)
* last version of branch 4.6 that support PHP 7.1 is [4.6.0](https://github.com/swoole/swoole-src/blob/v4.6.0/package.xml#L2029)
* after [4.6.1](https://github.com/swoole/swoole-src/blob/v4.6.1/package.xml#L1996), its only for PHP 7.2 or greater

```
diff --git a/build/ansible/group_vars/all/mods.yml b/build/ansible/group_vars/all/mods.yml
index 6052bb2..014b59a 100644
--- a/build/ansible/group_vars/all/mods.yml
+++ b/build/ansible/group_vars/all/mods.yml
@@ -992,6 +992,9 @@ extensions_available:
     7.0:
       type: pecl
       version: 4.2.13
+    7.1:
+      type: pecl
+      version: 4.6.0
     all:
       type: pecl
       command: yes yes | pecl install swoole
```

**Comment by llaville** [comment]
Finally, after my first comment (https://github.com/devilbox/docker-php-fpm/pull/193#issuecomment-778740210), **the fix is in wrong place**

You should modify only the jinja2 template file 
https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all/work.yml#L416

DRY principle, and use the Makefile `gen-dockerfiles` target

**Comment by llaville** [comment]
Last but not least: check-in the deprecation message 

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**Comment by llaville** [comment]
**WARNING** URL has changed again ! 

> Hi there!
>
> The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
>
>    https://bootstrap.pypa.io/pip/3.5/get-pip.py
>
> Sorry if this change causes any inconvenience for you!
>
> We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.
>
> There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the near future.
>
> Thanks for understanding!
>
> - Pradyun, on behalf of the volunteers who maintain pip.

**Comment by fibis** [comment]
Can we please merge this to get up-to-date images?

**Comment by cytopia** [comment]
Will be addressed here: https://github.com/devilbox/docker-php-fpm/pull/204

**Pull request closed without merging**
